### ISSUE TITLE
Checkpoints contains the meaning of each model？

### ISSUE THREAD

**Issue by swzaaaaaaa** [WeijingShi/Point-GNN#17]
![image](https://user-images.githubusercontent.com/43643616/83945042-7011b680-a83a-11ea-8668-64c2ca2f747a.png)
Excuse me，car_auto_T0_train，car_auto_T1_train ，car_fixed_T3_train and ped_cyl_auto_T3_trainval etc，What is the difference between these models？
In addition, how to directly train only pedestrian detection？

**Comment by WeijingShi** [comment]
Those checkpoints are used in the ablation study in the paper. Their names are in the format: ObjectType_AutoRegistration_GnnLayers_TrainingDataset.

For example: 
car_auto_T3_trainval = car detection that is trained on Kitti trainval split, the network has 3 gnn layers and enabled auto-registration. 

We have checkpoint ped_cyl_auto_T3_trainval to detect both pedestrians and cyclists. We provide the training [config](https://github.com/WeijingShi/Point-GNN/tree/master/configs) for that. Since it shares the same backbone, the additional detection of cyclists does not add significant overhead.  

We do not have pre-trained pedestrian-only models. You can add a pedestrian-only encoding method in [kitti_dataset.py](https://github.com/WeijingShi/Point-GNN/blob/3a17c1ec1279a421a33efd9bcab68249be3b5ed2/dataset/kitti_dataset.py#L1234), [train.py](https://github.com/WeijingShi/Point-GNN/blob/3a17c1ec1279a421a33efd9bcab68249be3b5ed2/train.py#L118), [eval.py](https://github.com/WeijingShi/Point-GNN/blob/3a17c1ec1279a421a33efd9bcab68249be3b5ed2/eval.py#L101) and [run.py](https://github.com/WeijingShi/Point-GNN/blob/3a17c1ec1279a421a33efd9bcab68249be3b5ed2/run.py#L248). You can use the configs for ped_cyl_auto_T3_trainval as a starting point for training. But remember to change the num_class in [config](https://github.com/WeijingShi/Point-GNN/blob/3a17c1ec1279a421a33efd9bcab68249be3b5ed2/configs/ped_cyl_auto_T3_trainval_config) to 4. 

Thanks,

**Comment by swzaaaaaaa** [comment]
Thank you very much for your answer. There is another question. If I want to test the ped_cyl_auto_T3_trainval model, do I need to download all the data sets according to the format you proposed?
