### ISSUE TITLE
Field of view

### ISSUE THREAD

**Issue by Juuustin** [WeijingShi/Point-GNN#25]
Hi, I test the algorithm on my dataset and find that the field of view is only about 120 degrees in front of the ego car.
I am wondering if this algorithm could detect 360 degrees of view.

**Comment by WeijingShi** [comment]
Hi @Juuustin, 

KITTI dataset only provides ground truth for the objects in front of the front camera.  That's why the code removes the points outside the front image when loading the point cloud [run.py Line 210](https://github.com/WeijingShi/Point-GNN/blob/2baf24f9556907f23e2e4018f1b756dac3f6c497/run.py#L210). A quick hack would be replacing get_cam_points_in_image_with_rgb with get_cam_points to process all points. But since the checkpoints are not trained with objects outside the view, the results would likely be messy. If you have your own dataset, it's better to retrain the model in the complete view.

**Comment by Juuustin** [comment]
> Hi @Juuustin,
> 
> KITTI dataset only provides ground truth for the objects in front of the front camera. That's why the code removes the points outside the front image when loading the point cloud [run.py Line 210](https://github.com/WeijingShi/Point-GNN/blob/2baf24f9556907f23e2e4018f1b756dac3f6c497/run.py#L210). A quick hack would be replacing get_cam_points_in_image_with_rgb with get_cam_points to process all points. But since the checkpoints are not trained with objects outside the view, the results would likely be messy. If you have your own dataset, it's better to retrain the model in the complete view.

Make sense, and thank you very much!
